### ISSUE TITLE
Problem with four steps

### ISSUE THREAD

**Issue by mvorisis** [gali8/G8SliderStep#1]
Hi 

When I'm adding one more step (4 steps) then the sliding image is out of the black circle only on first and fourth are in the correct shape.

**Comment by gali8** [comment]
Resize your image, because the images for the steps need to be with same size. Obviously you can put a small content inside them.

**Comment by iAmita** [comment]
Please follow 
https://stackoverflow.com/questions/47795449/smiley-rating-bar-swift/52443856#52443856
I have Done this for 5 Steps.
