### ISSUE TITLE
Error referencing this slider on controller

### ISSUE THREAD

**Issue by ghost** [gali8/G8SliderStep#2]
I did not succeed to use this component: Xcode 8.1 and Swift 2.3
Creating variable on lead to errors.

`@IBOutlet weak var slider1: G8SliderStep!`

<img width="447" alt="capture d ecran 2016-12-05 a 17 27 25" src="https://cloud.githubusercontent.com/assets/385357/20892915/3c841e9a-bb10-11e6-8697-638596e27520.png">

**Comment by gali8** [comment]
Strange... try to download the project in the master branch. It's working perfectly.
Do you forgot to import G8SliderStep ?

**Comment by ghost** [comment]
I dragged/dropped the file to my project as indicated.

It is as the class is not know by StoryBoard...

**Comment by gali8** [comment]
It's working for me. When you dragged/dropped it into the project, do you have checked the right target?

Anyway, here the sample project. Try it! => https://www.dropbox.com/s/85qva867c22anww/TestG9SliderStep.zip?dl=0
