### ISSUE TITLE
G8Slider not working on Swift 3

### ISSUE THREAD

**Issue by maclacerda** [gali8/G8SliderStep#5]
Hello Guy,

Congratulations for your job.

I have one problem while to use your library.

See this image: http://jmp.sh/aI3j6zW

My G8Slider step not appear properly in MyViewController

I'm using Swift 3 to my project and my view stored in XIB

Do you have any ideia of why problem occurring?

Thanks a lot

My code is:

```
leisureStep = G8SliderStep(frame: CGRect(x: 16, y: 80, width: 200, height: 50))
leisureStep.trackColor = UIColor( hexString: "#ced2bd")
        
leisureStep.stepTickColor = UIColor.orange
        
let shape = UIImage(named:"alps_entrada")!
leisureStep.tickImages = [shape, shape, shape, shape, shape]
leisureStep.stepTickWidth = 30
leisureStep.stepTickHeight = 30
leisureStep.trackHeight = 10
        
self.view.addSubview(leisureStep)
```

**Comment by gali8** [comment]
Sorry for the delay, did you fix it?

**Comment by maclacerda** [comment]
Hello, 

Yes,

Thanks for your help
